{
 "title": "Go runtime metrics",
 "description": "Go runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(go_goroutines, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(go_goroutines{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Reserved Memory",
   "type": "graph",
   "description": "Total bytes of memory reserved by the process.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: sys"
    }
   ]
  },
  {
   "title": "Stack Memory Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} stack inuse"
    }
   ]
  },
  {
   "title": "Other Memory Reservations",
   "type": "graph",
   "description": "Memory reservations by the runtime, not for stack or heap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: mspan sys"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: mcache sys"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: buck hash sys"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: gc sys"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "description": "Memory reserved, and actually in use, by the heap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: heap reserved"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: heap in use"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"tns_app\",instance=~\".*\"}",
     "legendFormat": "{{instance}}: heap alloc"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=~\"tns_app\",instance=~\".*\"}",
     "legendFormat": "{{instance}}: heap idle"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=~\"tns_app\",instance=~\".*\"}",
     "legendFormat": "{{instance}}: heap released"
    }
   ]
  },
  {
   "title": "Allocation Rate, Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}: malloc/min"
    }
   ]
  },
  {
   "title": "Heap Object Allocation Rate",
   "type": "graph",
   "description": "Rate of heap object allocation.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"$job\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}: mallocs per min"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"$job\", instance=~\"$instance\"} - go_memstats_frees_total{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: object count"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: {{quantile}}"
    }
   ]
  },
  {
   "title": "Next GC, Bytes",
   "type": "graph",
   "description": "The number used bytes at which runtime plans to perform the next GC.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}