// Code generated by gen_go_collector_metrics_set.go; DO NOT EDIT.
//go:generate go run gen_go_collector_metrics_set.go go1.17

//go:build go1.17 && !go1.18
// +build go1.17,!go1.18

package prometheus

var expectedRuntimeMetrics = map[string]string{
	"/gc/cycles/automatic:gc-cycles":              "go_gc_cycles_automatic_gc_cycles_total",
	"/gc/cycles/forced:gc-cycles":                 "go_gc_cycles_forced_gc_cycles_total",
	"/gc/cycles/total:gc-cycles":                  "go_gc_cycles_total_gc_cycles_total",
	"/gc/heap/allocs-by-size:bytes":               "go_gc_heap_allocs_by_size_bytes_total",
	"/gc/heap/allocs:bytes":                       "go_gc_heap_allocs_bytes_total",
	"/gc/heap/allocs:objects":                     "go_gc_heap_allocs_objects_total",
	"/gc/heap/frees-by-size:bytes":                "go_gc_heap_frees_by_size_bytes_total",
	"/gc/heap/frees:bytes":                        "go_gc_heap_frees_bytes_total",
	"/gc/heap/frees:objects":                      "go_gc_heap_frees_objects_total",
	"/gc/heap/goal:bytes":                         "go_gc_heap_goal_bytes",
	"/gc/heap/objects:objects":                    "go_gc_heap_objects_objects",
	"/gc/heap/tiny/allocs:objects":                "go_gc_heap_tiny_allocs_objects_total",
	"/gc/pauses:seconds":                          "go_gc_pauses_seconds_total",
	"/memory/classes/heap/free:bytes":             "go_memory_classes_heap_free_bytes",
	"/memory/classes/heap/objects:bytes":          "go_memory_classes_heap_objects_bytes",
	"/memory/classes/heap/released:bytes":         "go_memory_classes_heap_released_bytes",
	"/memory/classes/heap/stacks:bytes":           "go_memory_classes_heap_stacks_bytes",
	"/memory/classes/heap/unused:bytes":           "go_memory_classes_heap_unused_bytes",
	"/memory/classes/metadata/mcache/free:bytes":  "go_memory_classes_metadata_mcache_free_bytes",
	"/memory/classes/metadata/mcache/inuse:bytes": "go_memory_classes_metadata_mcache_inuse_bytes",
	"/memory/classes/metadata/mspan/free:bytes":   "go_memory_classes_metadata_mspan_free_bytes",
	"/memory/classes/metadata/mspan/inuse:bytes":  "go_memory_classes_metadata_mspan_inuse_bytes",
	"/memory/classes/metadata/other:bytes":        "go_memory_classes_metadata_other_bytes",
	"/memory/classes/os-stacks:bytes":             "go_memory_classes_os_stacks_bytes",
	"/memory/classes/other:bytes":                 "go_memory_classes_other_bytes",
	"/memory/classes/profiling/buckets:bytes":     "go_memory_classes_profiling_buckets_bytes",
	"/memory/classes/total:bytes":                 "go_memory_classes_total_bytes",
	"/sched/goroutines:goroutines":                "go_sched_goroutines_goroutines",
	"/sched/latencies:seconds":                    "go_sched_latencies_seconds",
}

const expectedRuntimeMetricsCardinality = 79
